### ISSUE TITLE
Suggestion/bug

### ISSUE THREAD

**Issue by cb12438** [win32kbase/MuckInternal#6]
Suggestions -

Add a flight button (basically inf jump)
Some speed hacks as well
A collect all resources on ground
Resource instamine (So you dount have to click "Break all Rocks" or "Break all trees"so you only break the one that your hitting)
Mob instakill (Same thing as i said with the rock and trees but with mobs)
Loot chests without gold
Add a setting menu where we can set keybinds for things

Bugs -
Some power ups not showing up im spawn menu
Aslo cant collect items i spawn in if i am not host (works when im host now)

**Comment by blakkkk** [comment]
If you want a client that can do most of those things use Mitch and MuckInternal: [https://github.com/ugackMiner53/Mitch-Client](https://github.com/ugackMiner53/Mitch-Client). They work great together

**Comment by win32kbase** [comment]
Most of these require patching and I am not really interested in implementing any patching API or anything atm. I did fix the serverside item spawner in the latest commit though. The power up bug is not fixable as far as I know as I mentioned earlier because those powerups just simply aren't in the allPowerups array.

**Comment by cb12438** [comment]
Maybe try finding the ID of the power up then use it like you did with the All power ups
